lim_g <- spTransform(lim, CRS(projection(predictors_b)))
Mydata <- data.frame(long=soil1a$long, lat=soil1a$lat, Tran030=soil1a$Tran, Tran0100=soil1a$Tran2) 
raster_stack <- stack(predictors_b)
#raster_stack <- aggregate(raster_stack, 5, mean)
raster_stack <- mask(raster_stack, lim_g)
remove(predictors_b)
library(MACHISPLIN)
#interp.rast<-machisplin.mltps(int.values=Mydata, covar.ras=raster_stack, n.cores=1, tps=TRUE)
 interp.rast <- readRDS('machinspline_CE_model_result.rds')
library(car)
lmbda1=(as.numeric(powerTransform(soil1$dummy, family ="bcPower")["lambda"]))
TOP <- (interp.rast[[1]]$final*lmbda1+1)^(1/lmbda1)
SUB <- (interp.rast[[2]]$final*lmbda1+1)^(1/lmbda1)
library(wesanderson)

plot(SUB, col= viridis::viridis(10), zlim=c(0,1), legend=FALSE)
 plot(SUB, col='yellow', zlim=c(1,100), add=TRUE, legend=FALSE)
legend("topright", legend = c("EC"), fill = viridis::viridis(10)))
